# Generated by Django 4.2.6 on 2023-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_stripe_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_api_key',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stripe аккаунт'),
        ),
    ]
