# Generated by Django 4.2.6 on 2023-10-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
