# Generated by Django 4.2.6 on 2023-11-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='usd', max_length=50, verbose_name='Валюта'),
        ),
    ]
