# Generated by Django 4.2.6 on 2023-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='currency',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='usd', max_length=50, verbose_name='Валюта'),
        ),
    ]
