# Generated by Django 4.2.6 on 2023-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Stripe ID'),
        ),
    ]
